server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.tcp.cpolar.cn:24250/useradmininfo?serverTimezone=GMT%2b8
    username: root
    password: 1234567890
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false


